### ISSUE TITLE
cupid can not booy by this kernel

### ISSUE THREAD

**Issue by pencc** [xiaomi-sm8450-kernel/android_kernel_platform_msm-kernel#1]
Hi, thanks for your work in sm8450, I try to pack Image into boot.img by /data/adb/magisk/magiskboot in Mi12. But the changed boot.img fail to boot Mi12, it's to fashboot cycle. Can you boot it? Is there any problem?

**Comment by ArianK16a** [comment]
Yes, it is booting - i'm generating the images in the lineage tree.

**Comment by ArianK16a** [comment]
Yes, the kernel works and is meant to be built like this: https://forum.xda-developers.com/t/development-of-lineageos-20-for-xiaomi-12-pro.4589247/
